import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import Hero from '@/components/Hero/Hero'
import Events from '@/components/Events/Events'
import Timeline from '@/components/Timeline/Timeline'



export default function Home() {
  return (
    <>
      <Head>
        <title>SOI 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Events />
        <Timeline />
      </Layout>
    </>
  )
}
