import Teams from "@/components/Teams/Teams";
import Head from "next/head";
import Layout from "@/components/Layout/Layout";
function Team() {
  return (
    <>
      <Head>
        <title>SOI 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/SOI_Favicon.png" />
      </Head>
      <Layout>
        <Teams />
      </Layout>
    </>
  );
}

export default Team;
