let timeLineData = [
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description: "Registrations Started.",
    date: "27th May - 31st May",
    color: "#B983FF",
    icon: "CodingClub",
  },
  {
    title: "Alokin - Analog",
    location: "",
    description: "First Checkpoint",
    date: "4th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description: "First Report Submission",
    date: "5th June EOD",
    color: "#B983FF",
    icon: "CodingClub",
  },
  {
    title: "Alokin - Digital",
    location: "",
    description: "First Checkpoint",
    date: "5th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description: "Second Report Submission",
    date: "12th June EOD",
    color: "#B983FF",
    icon: "CodingClub",
  },
  {
    title: "Alokin - Analog",
    location: "",
    description: "Second Checkpoint",
    date: "16th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description: "Third Report Submission",
    date: "24th June EOD",
    color: "#B983FF",
    icon: "CodingClub",
  },
  {
    title: "Alokin - Digital",
    location: "",
    description: "Second Checkpoint",
    date: "24th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Alokin - Analog",
    location: "",
    description: "Third Checkpoint",
    date: "30th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Alokin - Digital",
    location: "",
    description: "Third Checkpoint",
    date: "30th June EOD",
    color: "#FFB84C",
    icon: "Alokin",
  },
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description: "Final Report Submission",
    date: "7th July EOD",
    color: "#B983FF",
    icon: "CodingClub",
  },
  {
    title: "Toolset Unbounded",
    location: "Coding Club, IIT Dharwad",
    description:
      "Project Submission, everything that you have worked past 6 weeks on.",
    date: "9th July EOD",
    color: "#B983FF",
    icon: "CodingClub",
  },
]

export default timeLineData
